### ISSUE TITLE
Error on loading earthquakes.txt

### ISSUE THREAD

**Issue by dwuthrich** [kosho/ncedc-earthquakes#2]
I'm following along the steps to load the earthquake data.  After loading the logstash plugin and running  tail +1 earthquakes.txt| EVENT="earthquake" logstash/bin/logstash -f ncedc-earthquakes-logstash.conf

I get:

Settings: Default pipeline workers: 8
Invalid setting for elasticsearch output plugin:

  output {
    elasticsearch {
      # This setting must be a path
      # File does not exist or cannot be opened ./ncedc-earthquakes-template.json
      template => "./ncedc-earthquakes-template.json"
      ...
    }
  } {:level=>:error}
Pipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: Something is wrong with your configuration.>, :backtrace=>["/Users/dwuthrich/arches/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/config/mixin.rb:134:in `config_init'", "/Users/dwuthrich/arches/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/outputs/base.rb:63:in`initialize'", "/Users/dwuthrich/arches/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/output_delegator.rb:74:in `register'", "/Users/dwuthrich/arches/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181:in`start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/Users/dwuthrich/arches/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181:in`start_workers'", "/Users/dwuthrich/arches/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:136:in `run'", "/Users/dwuthrich/arches/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/agent.rb:473:in`start_pipeline'"], :level=>:error}
stopping pipeline {:id=>"main"}

Would appreciate any help

**Comment by kosho** [comment]
@dwuthrich You can specify the full path of the template in the ncedc-earthquakes-logstash.conf as the below example. Hope it works!

`template => "/Users/Kosho/repos/ncedc-earthquakes/ncedc-earthquakes-template.json"`

**Comment by kosho** [comment]
issue closed.
